server:
  port: 8080
spring:
  application:
    name: spring-demo
  datasource:
#    url:
#    username:
#    password:
#    driver-class-name:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
